application/maps/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint
from application.models import SurfSpot, Town
import os, requests


# global func
def get_weather_results(city_id, api_key):
    api_url = f"http://api.openweathermap.org/data/2.5/weather?id={city_id}&appid={api_key}&units=imperial"
    r = requests.get(api_url)
    return r.json()


maps_bp = Blueprint(
    'maps',
    __name__,
    template_folder='templates'
)

# @app.route('/')
# def root():
#     return redirect(url_for('index'))


@maps_bp.route('/surf-map')
def surf_map():
    return render_template('surf_map.html')


@maps_bp.route('/skate-map')
def skate_map():
    return render_template('skate_map.html')


@maps_bp.route('/<string:map>/<string:town>')
def map_town(map, town):
    spots = SurfSpot.query.join(Town).filter_by(town_name=town).all()
    town_obj = Town.query.filter_by(town_name=town).first()
    weather = get_weather_results(town_obj.open_weather_town_id,
                                  os.getenv('WEATHER_API_KEY'))
    return render_template('map_town.html', map=map, town=town,
                           town_obj=town_obj, spots=spots, weather=weather)


@maps_bp.route('/<string:map>/<string:town>/<string:spot>')
def town_spot(map, town, spot):
    spot = SurfSpot.query.filter(SurfSpot.spot_name == spot).join(Town).filter_by(town_name=town).first()
    return render_template('town_spot.html', map=map, town=town, spot=spot)


@maps_bp.route('/maps')
def maps():
    return render_template('maps.html')

application/templates/about.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Surf y Skate en PR</h2>
    <h3 style="text-align: center">Tu pagina web para que conozcas del surf y skate en Puerto Rico.</h3>
    <br>
    <br>

    <!-- surf image -->
    <div class="ui four column centered grid">
        <!-- <a href="{{ url_for('maps.surf_map')}}"><img class="ui large rounded image" src="/static/images/surf-4.jpg"></a> -->
        <a href="{{ url_for('maps.skate_map')}}"><img class="ui large rounded image" src="/static/images/soon-1.png"></a>
    </div>

    <!-- skate image -->
    <div class="ui two column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>
    
    <!-- divider -->
    <div class="ui four column centered grid">
        <div class="column">
            <h2 style="text-align: center"><i class="pr flag"></i></h2>
        </div>
    </div>

{% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Surf and Skate App - {% block title %}{% endblock %}</title>
    <!-- jQuery 1.8 or later, 33 KB -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Fotorama from CDNJS, 19 KB -->
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
    <!-- Semantic ui -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">
</head>
    <body>
        <nav>
            <ul>
                <li><a href="{{ url_for('users.index')}}" class="logo">Logo</a></li>
                {% if g.user.username %}
                    <li><a href="{{ url_for('auth.logout')}}">Sign out</a></li>
                    <li><a href="{{url_for('users.show', user_id=g.user.id)}}">Profile</a></li>
                    <li><a href="{{ url_for('posts.index', user_id=g.user.id)}}">Blog</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login')}}">Login</a></li>
                {% endif %}
                <li><a href="{{ url_for('users.index')}}">Community</a></li>
                <li><a href="{{ url_for('auth.about')}}">About</a></li>
                <li><a href="{{ url_for('maps.maps')}}">Maps</a></li>
            </ul>
        </nav>
        <br>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, msg in messages %}

                <div class="ui {{ category }} message compact">
                    <i class="close icon"></i>
                    <div class="header centered">
                        {{ msg }}
                    </div>
                </div>

                {% endfor %}
            {% endif %}
        {% endwith %}


        {% block content %}
        {% endblock %}
        <script type=text/javascript src="{{url_for('static', filename='js/scripts.js') }}"></script>
    </body>
</html>

application/templates/community.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Community Forum <i class="pr flag"></i></h2>
    <h3 style="text-align: center">Para que conectes con otros rippers alrededor de la isla!</h3>
    <br>
    <br>

    <!-- surf image -->
    <div class="ui four column centered grid">
        <a href="{{ url_for('maps.surf_map')}}"><img class="ui large rounded image" src="/static/images/surf-map-4.jpg"></a>
        <a href="{{ url_for('maps.skate_map')}}"><img class="ui large rounded image" src="/static/images/skate-map-2.jpg"></a>
    </div>

    <!-- skate image -->
    <div class="ui two column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>

    <!-- buttons -->
    <div class="ui four column centered grid">
        <div class="ui large buttons">
            <a href="{{ url_for('maps.surf_map')}}"><button class="ui blue button">Surf</button></a>
            <div class="or"></div>
            <a href="{{ url_for('maps.skate_map')}}"><button class="ui teal button">Skate</button></a>
        </div>
    </div>
    
    <!-- divider -->
    <div class="ui four column centered grid">
        <div class="column">
            <h2 style="text-align: center">Coming soon! <i class="pr flag"></i></h2>
        </div>
    </div>

    <!-- test -->



{% endblock %}

application/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Spots de Surf y Skate en Puerto Rico <i class="pr flag"></i></h2>
    <h3 style="text-align: center">Para que conozcas y ripees los lugares mas gufeaos alrededor de la isla!</h3>
    <br>
    <br>
    <!-- <div class="ui four column centered grid">
        <div class="column"><a href="{{ url_for('surf_map')}}"><img class="ui circular medium image" src="/static/images/surf.jpg"></a></div>
        <div class="column"><a href="{{ url_for('skate_map')}}"><img class="ui circular medium image" src="/static/images/skate-2.jpg"></a></div> 
    </div> -->

    <!-- surf image -->
    <div class="ui four column centered grid">
        <a href="{{ url_for('surf_map')}}"><img class="ui large rounded image" src="/static/images/surf-4.jpg"></a>
        <a href="{{ url_for('skate_map')}}"><img class="ui large rounded image" src="/static/images/skate-2.jpg"></a>
    </div>

    <!-- skate image -->
    <div class="ui two column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>

    <!-- buttons -->
    <div class="ui four column centered grid">
        <div class="ui large buttons">
            <a href="{{ url_for('surf_map')}}"><button class="ui blue button">Surf</button></a>
            <div class="or"></div>
            <a href="{{ url_for('skate_map')}}"><button class="ui teal button">Skate</button></a>
        </div>
    </div>
    
    <!-- divider -->
    <div class="ui four column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>

    <!-- test -->



{% endblock %}

application/templates/maps.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Surf and Skate Maps</h2>
    <h3 style="text-align: center">Haz click en las imagenes para que encuentres spots alrededor de la isla!</h3>
    <br>
    <br>

    <!-- surf image -->
    <div class="ui four column centered grid">
        <a href="{{ url_for('maps.surf_map')}}"><img class="ui large rounded image" src="/static/images/surf-map-4.jpg"></a>
        <a href="{{ url_for('maps.skate_map')}}"><img class="ui large rounded image" src="/static/images/skate-map-2.jpg"></a>
    </div>

    <!-- skate image -->
    <div class="ui two column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>
    
    <!-- divider -->
    <div class="ui four column centered grid">
        <div class="column">
            <h2 style="text-align: center"> <i class="pr flag"></i></h2>
        </div>
    </div>

    <!-- test -->



{% endblock %}