application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class PostForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    post_body = StringField('Blog Post Body', [validators.DataRequired()])


class DeleteForm(FlaskForm):
    pass

application/posts/routes.py
from flask import (render_template, request,
                   redirect, url_for, Blueprint)
from application.posts.forms import PostForm, DeleteForm
from application.models import User, Post
from application import db
import datetime
from decorators import ensure_authenticated, ensure_correct_user

posts_bp = Blueprint(
    'posts',
    __name__,
    template_folder='templates'
)


# posts index
@posts_bp.route('/', methods=['GET', 'POST'])
@ensure_authenticated
def index(user_id):
    date = datetime.datetime.now().strftime('%A, %b %d, %Y')
    delete_form = DeleteForm()
    found_user = User.query.get(user_id)
    if request.method == 'POST':
        form = PostForm(request.form)
        if form.validate():
            new_posts = Post(request.form['title'], datetime.datetime.now(),
                             request.form['post_body'], user_id)
            db.session.add(new_posts)
            db.session.commit()
            return redirect(url_for('posts.index', user_id=user_id))
        else:
            return render_template('posts/new.html', form=form)
    return render_template('posts/index.html', user=found_user,
                           delete_form=delete_form, date=date)


# posts new
@posts_bp.route('/new', methods=['GET', 'POST'])
@ensure_authenticated
@ensure_correct_user
def new(user_id):
    found_user = User.query.get(user_id)
    post_form = PostForm()
    return render_template('posts/new.html', user=found_user, form=post_form)


# posts edit
@posts_bp.route('/<int:id>/edit')
@ensure_authenticated
@ensure_correct_user
def edit(user_id, id):
    found_post = Post.query.get(id)
    post_form = PostForm(obj=found_post)
    return render_template('posts/edit.html', post=found_post, form=post_form)


# posts show
@posts_bp.route('/<int:id>',  methods=['GET', 'PATCH', 'DELETE'])
@ensure_authenticated
@ensure_correct_user
def show(user_id, id):
    found_post = Post.query.get(id)
    found_user = User.query.get(user_id)
    if request.method == b"PATCH":
        found_post.title = request.form["title"]
        found_post.post_body = request.form["post_body"]
        db.session.add(found_post)
        db.session.commit()
        return redirect(url_for('posts.index', user_id=user_id))
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(found_post)
            db.session.commit()
        return redirect(url_for('posts.index', user_id=user_id))
    return render_template('posts/show.html', post=found_post, user=found_user)

application/posts/templates/posts/edit.html
{% extends "base.html" %}

{% block title %}Edit a blog post{% endblock %}

{% block content %}

    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Edit Blog Post</h2>
            <div class="ui clearing divider"></div>
            <p>What are you thinking today?</p>

            <form class="ui form" method="POST" action="{{ url_for('posts.show', user_id=post.user_id, id=post.id) }}?_method=PATCH">
                {{ form.hidden_tag() }}
                {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="field">
                        {{field.label}}
                        {{field}}
                        <span>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

application/posts/templates/posts/index.html
{% extends "base.html" %}

{% block title %}Blog Homepage{% endblock %}

{% block content %}

<div class="ui center aligned icon header">
    <i class="pencil alternate icon"></i>
    {% if g.user.id == user.id %}
        <h1>Hi {{g.user.username}}! These are your current blog posts.</h1>
    {% else %}
        <h1>Hi {{g.user.username}}! These are {{user.username}}'s blog posts.</h1>
    {% endif %}

<p>{{ date }} - <span id="clock"></span></p>
<a href="{{ url_for('posts.new', user_id=user.id) }}">Add Post</a>
</div>
  
<div class="ui divider"></div>

<div class="ui four column grid centered">

    {% for post in user.posts %} 

        <div class="column">
            <div class="ui centered cards">
                <div class="card">
                    <div class="content">
                        <img class="right floated mini ui image" src="/static/images/matthew.png">
                        <div class="header">
                            <a href="{{url_for('posts.show', user_id=user.id, id=post.id)}}">{{post.title}}</a>
                        </div>
                        <div class="meta">
                            {{post.date.strftime('%Y-%m-%d') }}
                        </div>
                        <div class="description">
                            {{post.post_body}}
                        </div>
                    </div>
                    <div class="extra content">
                        <div class="ui two buttons">
                            <div class="ui basic blue button"><a href="{{ url_for('posts.edit', user_id=user.id, id=post.id) }}">Edit</a></div>
                            <div class="ui basic red button"><form action="{{url_for('posts.show', user_id=user.id, id=post.id)}}?_method=DELETE" method="POST">
                                {{delete_form.hidden_tag()}}
                                <input type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %} 
</div>

{% endblock %}

application/posts/templates/posts/new.html
{% extends "base.html" %}

{% block title %}Add a Blog Post{% endblock %}

{% block content %}
    
<div class="ui two column centered grid">
    <div class="column"><div class="ui segment">
        <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Add a Blog Post</h2>
        <div class="ui clearing divider"></div>
        <p>What are you thinking today?{{user.id}}||||{{g.user.id}}||{{session['user_id']}}</p>

        <form class="ui form" method="POST" action="{{ url_for('posts.index', user_id=user.id) }}">
            {{ form.hidden_tag() }}
            {% for field in form if field.widget.input_type != 'hidden' %}
                <div class="field">
                    {{field.label}}
                    {{field}}
                    <span>
                        {% if field.errors %}
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        {% endif %}
                    </span>
                </div>
            {% endfor %}
            <button class="ui button" type="submit">Save</button>
        </form>
    </div>
</div>

{% endblock %}

application/posts/templates/posts/show.html
{% extends "base.html" %}

{% block title %}Blog Post page.{% endblock %}

{% block content %}

    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header">{{ post.id }}. {{ post.user_id }}.{{ post.title }}</h2>
            <div class="ui clearing divider"></div>
            <h5>Written on {{ post.date }}</h5>
            <p>{{ post.post_body }}</p>
            <a href="{{ url_for('posts.index', user_id=user.id) }}">See all the posts.</a>
            <br>
            <button class="ui button"><a href="{{ url_for('posts.edit', user_id=user.id, id=post.id) }}">Edit Blog Post</a></button>

        </div>
    </div>

{% endblock %}