application/maps/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint
from application.models import SurfSpot, Town
import os, requests


# global func
def get_weather_results(city_id, api_key):
    api_url = f"http://api.openweathermap.org/data/2.5/weather?id={city_id}&appid={api_key}&units=imperial"
    r = requests.get(api_url)
    return r.json()


maps_bp = Blueprint(
    'maps',
    __name__,
    template_folder='templates'
)

# @app.route('/')
# def root():
#     return redirect(url_for('index'))


@maps_bp.route('/surf-map')
def surf_map():
    return render_template('surf_map.html')


@maps_bp.route('/skate-map')
def skate_map():
    return render_template('skate_map.html')


@maps_bp.route('/<string:map>/<string:town>')
def map_town(map, town):
    spots = SurfSpot.query.join(Town).filter_by(town_name=town).all()
    town_obj = Town.query.filter_by(town_name=town).first()
    weather = get_weather_results(town_obj.open_weather_town_id,
                                  os.getenv('WEATHER_API_KEY'))
    return render_template('map_town.html', map=map, town=town,
                           town_obj=town_obj, spots=spots, weather=weather)


@maps_bp.route('/<string:map>/<string:town>/<string:spot>')
def town_spot(map, town, spot):
    spot = SurfSpot.query.filter(SurfSpot.spot_name == spot).join(Town).filter_by(town_name=town).first()
    return render_template('town_spot.html', map=map, town=town, spot=spot)


@maps_bp.route('/maps')
def maps():
    return render_template('maps.html')

application/maps/templates/map_town.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    {% if map == "surf-map" %}
    <h2 style="text-align: center">Surf Spots en: {{ town.title() }}</h2>
    {% elif map == "skate-map" %}
    <h2 style="text-align: center">Skate Spots en: {{ town.title() }}</h2>
    {% endif %}
    <h3 style="text-align: center">Para que conozcas y ripees los lugares mas gufeaos!</h3>
    <h4 style="text-align: center">Temperatura actual: {{ weather['main'].temp|round|int }}°F</h4>
    <br>
    <br>

    <!-- img carousel -->
    <div class="ui two column centered grid">
        <div class="fotorama"
            data-nav="thumbs"
            data-loop="true"
            data-keyboard="true">
            <img data-caption="Tres Palmas" src="/static/images/surf.jpg">
            <img src="/static/images/gas-chambers.jpg" data-caption="Gas Chambers">
            <img src="/static/images/punta-borinquen.jpg" data-caption="Aguadilla">
            <img src="/static/images/gas-chambers-2.jpg" data-caption="Gas Chambers">
            <img src="/static/images/tres-palmas.jpg" data-caption="Tres Palmas">
            <img src="/static/images/tres-palmas-2.jpg" data-caption="Tres Palmas">
            <img src="/static/images/surf.jpg" data-caption="Tres Palmas">
            <img src="/static/images/gas-chambers.jpg" data-caption="Gas Chambers">
            <img src="/static/images/punta-borinquen.jpg" data-caption="Punta Borinquen">
            <img src="/static/images/gas-chambers-2.jpg" data-caption="Gas Chambers">
            <img src="/static/images/tres-palmas.jpg" data-caption="Tres Palmas">
            <img src="/static/images/tres-palmas-2.jpg" data-caption="Tres Palmas">
        </div>
    </div>

    <!-- paragraph -->
    <div class="ui two column centered grid">
        <div class="column">
            <!-- divider -->
            <div class="ui section divider"></div>
            <p>{{ town_obj.town_surf_descr }}</p>
            <!-- divider -->
            <div class="ui section divider"></div>
        </div>
    </div>

    <h2 style="text-align: center">Surf Spots en: {{ town.title() }}</h2>
    <h5 style="text-align: center">{{ town_obj.town_descr}}</h5>
    <br>

    <!-- divider -->
    <div class="ui grid centered">
        <div class="four wide column"><div class="ui section divider"></div></div>
        <!-- <div class="four wide column"></div>
        <div class="four wide column"></div>
        <div class="four wide column"></div> -->
      </div>

  <!-- spots -->
  <div class="ui stackable two column centered grid">
    <div class="column">
      <div class="ui three cards">
      {% for spot in spots %}
        <a class="red card" href="{{ url_for('maps.town_spot', map=map, town=town, spot=spot.spot_name ) }}">
          <div class="image">
            <img src="/static/images/surf.jpg">
          </div>
          <div class="content">
            <div class="center aligned header">{{ spot.spot_name }}</div>
          </div>
        </a>
      {% endfor %}
    </div></div>
    <div class="four column centered row">
      <div class="column"></div>
      <div class="column"></div>
    </div>
  </div>

      <!-- divider -->
      <div class="ui grid centered">
        <div class="four wide column"><div class="ui section divider"></div></div>
        <!-- <div class="four wide column"></div>
        <div class="four wide column"></div>
        <div class="four wide column"></div> -->
      </div>    

{% endblock %}

application/maps/templates/town_spot.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Surf Spot: {{ spot.spot_name }}</h2>
    <h3 style="text-align: center"> En el pueblo de {{ spot.town.town_name }}.</h3>
    <br>
    <br>

    <!-- img carousel -->
    <div class="ui two column centered grid">
        <div class="fotorama"
            data-nav="thumbs"
            data-loop="true"
            data-keyboard="true">
            <img data-caption="Tres Palmas" src="/static/images/surf.jpg">
            <img src="/static/images/gas-chambers.jpg" data-caption="Gas Chambers">
            <img src="/static/images/punta-borinquen.jpg" data-caption="Aguadilla">
            <img src="/static/images/gas-chambers-2.jpg" data-caption="Gas Chambers">
            <img src="/static/images/tres-palmas.jpg" data-caption="Tres Palmas">
            <img src="/static/images/tres-palmas-2.jpg" data-caption="Tres Palmas">
            <img src="/static/images/surf.jpg" data-caption="Tres Palmas">
            <img src="/static/images/gas-chambers.jpg" data-caption="Gas Chambers">
            <img src="/static/images/punta-borinquen.jpg" data-caption="Punta Borinquen">
            <img src="/static/images/gas-chambers-2.jpg" data-caption="Gas Chambers">
            <img src="/static/images/tres-palmas.jpg" data-caption="Tres Palmas">
            <img src="/static/images/tres-palmas-2.jpg" data-caption="Tres Palmas">
        </div>
    </div>

    <!-- paragraph -->
    <div class="ui two column centered grid">
        <div class="column">
            <!-- divider -->
            <div class="ui section divider"></div>
            <p>Description of the spot {{ spot.spot_descr }}. Te eum doming eirmod, nominati pertinacia argumentum ad his. Ex eam alia facete scriptorem, est autem aliquip detraxit at. Usu ocurreret referrentur at, cu epicurei appellantur vix. Cum ea laoreet recteque electram, eos choro alterum definiebas in. Vim dolorum definiebas an. Mei ex natum rebum iisque.Te eum doming eirmod, nominati pertinacia argumentum ad his. Ex eam alia facete scriptorem, est autem aliquip detraxit at. Usu ocurreret referrentur at, cu epicurei appellantur vix. Cum ea laoreet recteque electram, eos choro alterum definiebas in. Vim dolorum definiebas an. Mei ex natum rebum iisque.</p>
            <!-- divider -->
            <div class="ui section divider"></div>
        </div>
    </div>

{% endblock %}