application/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators, SubmitField


class UserForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])


class DeleteForm(FlaskForm):
    pass


class LoginForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])


# follow or unfollow form
class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

application/users/routes.py
from flask import (render_template, request,
                   redirect, url_for, session,
                   flash, Blueprint, g)
from application.users.forms import UserForm, DeleteForm, EmptyForm
from application.models import User
from application import db, bcrypt
import datetime
from sqlalchemy.exc import IntegrityError
from decorators import (ensure_authenticated,
                        prevent_login_signup,
                        ensure_correct_user)

users_bp = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)


# users
@users_bp.route('/')
@ensure_authenticated
def index():
    date = datetime.datetime.now().strftime('%A, %b %d, %Y')
    delete_form = DeleteForm()
    return render_template('users/index.html',
                           users=User.query.all(),
                           delete_form=delete_form,
                           date=date)


# user signup
@users_bp.route('/', methods=['POST'])
@prevent_login_signup
def signup():
    form = UserForm(request.form)
    if form.validate():
        try:
            new_user = User(form.username.data,
                            form.password.data,
                            form.first_name.data,
                            form.last_name.data,
                            datetime.datetime.now())
            db.session.add(new_user)
            db.session.commit()
            session['user_id'] = new_user.id
            flash('User Created!', 'positive')
            return redirect(url_for('users.index'))
        except IntegrityError:
            return render_template('users/new.html', form=form)
        return render_template('users/new.html', form=form)


# users new
@users_bp.route('/new')
@prevent_login_signup
def new():
    user_form = UserForm()
    return render_template('users/new.html', form=user_form)


# users edit
@users_bp.route('/<int:user_id>/edit')
@ensure_authenticated
@ensure_correct_user
def edit(user_id):
    found_user = User.query.get(user_id)
    user_form = UserForm(obj=found_user)
    return render_template('users/edit.html', user=found_user, form=user_form)


# users show
@users_bp.route('/<int:user_id>', methods=['GET', 'PATCH', 'DELETE'])
@ensure_authenticated
def show(user_id):
    empty_form = EmptyForm()
    found_user = User.query.get(user_id)
    delete_form = DeleteForm()
    if request.method == b'PATCH':
        form = UserForm(request.form)
        if form.validate():
            found_user.username = form.username.data
            found_user.password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
            db.session.add(found_user)
            db.session.commit()
            flash('User Updated!', 'positive')
            return redirect(url_for('users.index'))
        return render_template('users/edit.html', user=found_user, form=form)
    if request.method == b'DELETE':
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(found_user)
            db.session.commit()
            session.pop('user_id')
            flash('User Deleted!', 'positive')
        return redirect(url_for('auth.login'))
    return render_template('users/show.html',
                           user=found_user,
                           empty_form=empty_form,
                           delete_form=delete_form)

# follow and unfollow routes
@users_bp.route('/follow/<int:user_id>', methods=['POST'])
@ensure_authenticated
def follow(user_id):
    form = EmptyForm()
    curr_user_obj = g.user
    found_user = User.query.get(user_id)
    if form.validate_on_submit():
        if found_user is None:
            flash('User not found!', 'negative')
            return redirect(url_for('users.index'))
        if found_user == curr_user_obj:
            flash('You cannot follow yourself!')
            return redirect(url_for('users.show', user_id=found_user.id))
        curr_user_obj.follow(found_user)
        db.session.commit()
        flash(f'You are following {found_user.username}!', 'positive')
        return redirect(url_for('users.show', user_id=found_user.id))
    else:
        return redirect(url_for('users.index'))


@users_bp.route('/unfollow/<int:user_id>', methods=['POST'])
@ensure_authenticated
def unfollow(user_id):
    form = EmptyForm()
    found_user = User.query.get(user_id)
    curr_user_obj = g.user
    if form.validate_on_submit():
        if found_user is None:
            flash('User not found!', 'negative')
            return redirect(url_for('users.index'))
        if found_user == curr_user_obj:
            flash('You cannot unfollow yourself!', 'negative')
            return redirect(url_for('users.show', user_id=found_user.id))
        curr_user_obj.unfollow(found_user)
        db.session.commit()
        flash(f'You are not following {found_user.username}!', 'negative')
        return redirect(url_for('users.show', user_id=found_user.id))
    else:
        return redirect(url_for('users.index'))

application/users/templates/users/edit.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <br>
    <h2 style="text-align: center">Edit user! <i class="pr flag"></i></h2>
    <h3 style="text-align: center">Para que conectes con otros rippers alrededor de la isla!</h3>
    <br>
    <br>

    <!-- new user form -->
    <div class="ui four column centered grid">
        <form action="{{url_for('show', id=user.id)}}?_method=PATCH" method="POST">
            <input type="text" name="first_name" value="{{ user.first_name }}">
            <input type="text" name="last_name" value="{{ user.last_name }}">
            <input type="submit" value="Save">
        </form>
    </div>

    <!-- divider -->
    <div class="ui two column centered grid">
        <div class="column">
            <div class="ui section divider"></div>
        </div>
    </div>

    <!-- buttons -->
    <div class="ui four column centered grid">
        <div class="ui large buttons">
            <a href="{{ url_for('surf_map')}}"><button class="ui blue button">Surf</button></a>
            <div class="or"></div>
            <a href="{{ url_for('skate_map')}}"><button class="ui teal button">Skate</button></a>
        </div>
    </div>
    
    <!-- divider -->
    <div class="ui four column centered grid">
        <div class="column">
            <h2 style="text-align: center">Coming soon! <i class="pr flag"></i></h2>
        </div>
    </div>

    <!-- test -->



{% endblock %}

application/users/templates/users/index.html
{% extends "base.html" %}

{% block title %}All users{% endblock %}

{% block content %}

<div class="ui center aligned icon header">
    <i class="users icon"></i>
    <h1>Hi {{ g.user.username }}! Meet our friends in the community.</h1>

<p>{{ date }} - <span id="clock"></span></p>
</div>

<div class="ui divider"></div>

<div class="ui four column grid centered">

    {% for user in users %}
      {% if g.user.id != user.id %}
        <div class="column">
            <div class="ui centered cards">
                <div class="card">
                    <div class="content">
                        <img class="right floated mini ui image" src="/static/images/matthew.png">
                        <div class="header">
                            <a href="{{url_for('users.show', user_id=user.id)}}">{{user.username}}</a>
                        </div>
                        <div class="meta">
                        Member since {{user.date.strftime('%Y-%m-%d')}}
                        </div>
                        <div class="description">
                        Elliot requested permission to view your contact details.
                        </div>
                    </div>
                    <div class="extra content">
                        <div class="ui two buttons">
                            <div class="ui basic green button"><a href="{{ url_for('posts.index', user_id=user.id) }}">Blog Posts</a></div>
                            <div class="ui basic blue button"><a href="{{url_for('users.show', user_id=user.id)}}">Profile</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      {% endif %}
    {% endfor %}
</div>

{% endblock %}

application/users/templates/users/new.html
{% extends "base.html" %}

{% block title %}Add a user{% endblock %}

{% block content %}

    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Create an Account</h2>
            <div class="ui clearing divider"></div>
            <p>Already a member? <a href="{{ url_for('auth.login') }}">Login!</a></p>

            <form class="ui form" method="POST" action="{{url_for('users.index')}}">
                {{ form.hidden_tag() }}
                {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="field">
                        {{field.label}}
                        {{field}}
                        <span>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

application/users/templates/users/show.html
{% extends "base.html" %}

{% block title %}User Page{% endblock %}

{% block content %}

<div class="ui centered link card">
    <a class="image" href="{{ url_for('posts.index', user_id=user.id) }}">
        <img src="/static/images/matthew.png">
    </a>

    <div class="content">
        <a class="header" href="{{ url_for('posts.index', user_id=user.id) }}">{{user.username}}</a>
            <div class="meta">
                <span class="date">Member since {{ user.date.strftime('%Y-%m-%d') }}</span>
            </div>

        <div class="description">
            <!-- session user id == user url id show personalized card-->
            {% if g.user.id == user.id %}
                {% if g.user.posts.count() == 1 %}
                    <p>You have {{ g.user.posts.count() }} post.</p>
                    <a href="{{ url_for('posts.index', user_id=g.user.id) }}">Click to add more!</a>
                {% elif g.user.posts.count() == 0 %}
                    <p>You have {{ g.user.posts.count() }} posts.</p>
                    <a href="{{ url_for('posts.index', user_id=g.user.id) }}">Click to add a one!</a>
                {% elif g.user.posts.count() > 1 %}
                    <p>You have {{ g.user.posts.count() }} posts.</p>
                    <a href="{{ url_for('posts.index', user_id=g.user.id) }}">Click to check them out!</a>
                {% endif%}
            {% else %}
            <!-- non personalized card elements -->
                {% if user.posts.count() == 1 %}
                    <p>Your friend has {{ user.posts.count() }} post.</p>
                    <a href="{{ url_for('posts.index', user_id=user.id) }}">Click to add more!</a>
                {% elif user.posts.count() == 0 %}
                    <p>Your friend has {{ user.posts.count() }} posts.</p>
                    <a href="{{ url_for('posts.index', user_id=user.id) }}">Click to add a one!</a>
                {% else %}
                    <p>Your friend has {{ user.posts.count() }} posts.</p>
                    <a href="{{ url_for('posts.index', user_id=user.id) }}">Click to check them out!</a>
                {% endif%}
            {% endif%}
        </div>
    </div>
    <div class="extra content">
        <a>
            <i class="user icon"></i>
            {% if user.followers.count() == 1 %}
                {{ user.followers.count() }} follower, {{ user.followed.count() }} following.
            {% else %}
                {{ user.followers.count() }} followers, {{ user.followed.count() }} following.
            {% endif %}
        </a>
        <div class="fluid ui buttons">
            {% if g.user.id == user.id %}
                <button class="ui basic blue button"><a href="{{ url_for('users.edit', user_id=user.id) }}">Edit</a></button>
                <button class="ui basic red button">
                    <form action="{{url_for('users.show', user_id=user.id)}}?_method=DELETE" method="POST">
                        {{delete_form.hidden_tag()}}
                        <input type="submit" value="Delete">
                    </form>
                </button>
            {% elif not g.user.is_following(user) %}
                <button class="ui basic blue button">
                    <form action="{{ url_for('users.follow', user_id=user.id) }}" method="post">
                        {{ empty_form.hidden_tag() }}
                        {{ empty_form.submit(value='Follow') }}
                    </form>
                </button>
            {% else %}
                <button class="ui basic red button">
                    <form action="{{ url_for('users.unfollow', user_id=user.id) }}" method="post">
                        {{ empty_form.hidden_tag() }}
                        {{ empty_form.submit(value='Unfollow') }}
                    </form>
                </button>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}